import { Activity, ExternalLink, Hash, RefreshCw, Rows3, ShieldCheck } from 'lucide-react';
import { getContractAddress, getExplorerContractUrl, getNetwork } from '../config';
import { toHex } from '../lib/midnight';
import { useContractState } from '../hooks/useContractState';

export default function LedgerPage() {
  const address = getContractAddress();
  const { ledgerState, isLoading, error, lastUpdate, refetch } = useContractState(7000);
  const tokens: string[] = [];
  try { if (ledgerState?.redeemed_tokens?.[Symbol.iterator]) for (const item of ledgerState.redeemed_tokens) tokens.push(toHex(item)); } catch { /* generated set shape can vary */ }
  const fill = ledgerState ? Math.min(100, Number(ledgerState.claims || 0) / Math.max(1, Number(ledgerState.claim_limit || 1)) * 100) : 0;
  return <div className="page"><div className="page-intro"><div><span className="label">Your workspace</span><h1>Read the space.<br />Not the person.</h1><p>Public state is useful when it is intentional. This page mirrors the exact configuration and aggregate receipts that Stillwater discloses.</p></div><button className="button" onClick={() => void refetch()} disabled={isLoading}><RefreshCw size={15} className={isLoading ? 'spin' : ''} />Refresh state</button></div>
    {!address && <div className="notice warning" role="status"><Rows3 size={15} style={{verticalAlign:'-3px',marginRight:7}} />No contract address is configured for {getNetwork()}. Deploy a new space from <a className="text-link" href="/admin">Operator studio</a>.</div>}{error && <div className="notice error" role="alert">{error}<p>Check the network, address and indexer before submitting a private claim.</p></div>}
    <div className="metrics-row ledger-metrics"><div className="metric"><span className="metric-icon"><Hash size={18} /></span><div><p>Receipts</p><strong>{ledgerState?.claims?.toString() || '—'}</strong></div></div><div className="metric"><span className="metric-icon"><Rows3 size={18} /></span><div><p>Capacity</p><strong>{ledgerState?.claim_limit?.toString() || '—'}</strong></div></div><div className="metric"><span className="metric-icon"><Activity size={18} /></span><div><p>Space status</p><strong>{ledgerState ? ledgerState.room_open ? 'OPEN' : 'LOCKED' : '—'}</strong></div></div></div>
    <div className="two-col"><section className="panel"><div className="section-heading"><h2>Published policy</h2><span className="status-badge"><span className="network-dot" />{getNetwork()}</span></div>{isLoading && !ledgerState ? <div className="empty-state compact"><RefreshCw className="spin" size={20} />Syncing public state…</div> : !ledgerState ? <div className="empty-state compact"><Rows3 size={25} /><h2>No indexed state</h2><p>Once the deployment is included, public policy fields will appear here.</p></div> : <><div className="data-list"><div className="data-row"><span>Contract</span><a className="text-link mono" href={getExplorerContractUrl(address)} target="_blank" rel="noreferrer">{address.slice(0, 10)}… <ExternalLink size={12} /></a></div><div className="data-row"><span>Threshold</span><strong>{ledgerState.claim_threshold?.toString()} / 100</strong></div><div className="data-row"><span>Room fingerprint</span><strong className="mono">{toHex(ledgerState.room_id).slice(0, 18)}…</strong></div><div className="data-row"><span>Claim closes</span><strong>{new Date(Number(ledgerState.claim_expiry) * 1000).toLocaleString()}</strong></div><div className="data-row"><span>Issuer label</span><strong className="mono">{toHex(ledgerState.issuer_id).slice(0, 18)}…</strong></div></div><div className="label" style={{marginTop:20}}>Capacity used</div><div className="progress" aria-label={`${fill.toFixed(1)} percent of capacity used`}><span style={{width:`${fill}%`}} /></div><div className="progress-label">{fill.toFixed(1)}% of the public space</div></>}</section>
      <section className="panel"><div className="section-heading"><h2>Anonymous receipts</h2><span className="status-badge positive"><span />Public feed</span></div><p>Each token proves that a room-scoped secret was accepted once. It is not a name, wallet address, score, or source credential.</p>{tokens.length === 0 ? <div className="empty-state compact"><ShieldCheck size={25} /><h2>Nothing to see yet.</h2><p>The first accepted claim will leave an anonymous receipt here.</p></div> : <div className="feed">{tokens.slice().reverse().map((item, index) => <div className="data-row" key={item}><span><Hash size={13} style={{verticalAlign:'-2px',marginRight:6}} />Receipt {tokens.length - index}</span><strong className="mono">{item.slice(0, 18)}…</strong></div>)}</div>}{lastUpdate && <div className="progress-label" style={{marginTop:20}}><Activity size={13} />Last indexed read · {lastUpdate.toLocaleTimeString()}</div>}</section></div>
    <div className="honesty-note"><ShieldCheck size={15} /><p>Public does not mean everything. The ledger reveals the shape of the policy and the fact of a receipt; it does not reveal the witness values used to produce it. <a href="/privacy">See the full boundary.</a></p></div></div>;
}
