import { ArrowRight, Check, Eye, Fingerprint, LockKeyhole, ShieldCheck, TriangleAlert } from 'lucide-react';
import { Link } from 'react-router-dom';

export default function PrivacyPage() {
  return <div className="page privacy-page">
    <div className="page-intro"><div><span className="label">The trust model</span><h1>Privacy is a boundary.<br />Here’s exactly where ours sits.</h1><p>Zero knowledge is useful when you know what is — and isn’t — being kept private.</p></div></div>
    <div className="privacy-banner"><img src="/images/summit.jpg" alt="A mountain summit rising above layers of cloud" width="900" height="600" /><div><ShieldCheck size={29} strokeWidth={1.5} /><h2>Less information.<br />Not less accountability.</h2><p>Stillwater proves a private score satisfies a public rule. It doesn’t publish the score to do it.</p></div></div>
    <div className="two-col boundary-grid"><section className="panel"><div className="section-heading"><span className="icon-tile"><Eye size={22} /></span><span className="status-badge">On the ledger</span></div><h2>What an observer can see</h2><p>These values are deliberately public and available in the ledger view.</p><ul className="detail-list"><li><Check size={16} /><div><strong>The access policy</strong><p>Threshold, expiry, capacity, room identifier, issuer label and whether the room is open.</p></div></li><li><Check size={16} /><div><strong>The outcome of a claim</strong><p>The aggregate count and a room-scoped redemption token. The receipt is not a name.</p></div></li><li><Check size={16} /><div><strong>Transaction metadata</strong><p>The called contract and circuit, transaction timing, ledger reads and writes, and public transaction data.</p></div></li><li><Check size={16} /><div><strong>Operator commitment</strong><p>A domain-separated hash used to verify knowledge of the operator secret.</p></div></li></ul></section>
    <section className="panel private-boundary"><div className="section-heading"><span className="icon-tile"><LockKeyhole size={22} /></span><span className="status-badge positive">Private witnesses</span></div><h2>What the circuit keeps private</h2><p>These inputs are provided by witness callbacks, not public circuit arguments.</p><ul className="detail-list"><li><Fingerprint size={16} /><div><strong>Your eligibility score</strong><p>The circuit checks 0–100 and the public minimum. The actual value is not stored on-chain.</p></div></li><li><Fingerprint size={16} /><div><strong>Your access secret</strong><p>Used to derive a one-time token for this room. High-entropy randomness makes recovering the secret infeasible.</p></div></li><li><Fingerprint size={16} /><div><strong>The operator secret</strong><p>Authorizes room management without putting that secret in the public ledger.</p></div></li></ul><div className="notice">Private means not disclosed on-chain. The app, wallet, and any configured proving service still belong to your trust boundary.</div></section></div>
    <section className="panel limitations"><div className="section-heading"><h2>Important, without the fine print.</h2><TriangleAlert size={21} /></div><div className="limitations-grid"><div><h3>A proof isn’t a credential.</h3><p>This MVP accepts a self-attested score. An invented score can satisfy the circuit. No issuer signature, real-world age or approved membership is verified. The issuer field is a public label, not an attestation.</p></div><div><h3>One secret isn’t one person.</h3><p>The same secret cannot claim twice in a room. A new secret can make another claim. This is replay protection, not Sybil resistance. Do not use it as a production allowlist or identity gate.</p></div><div><h3>No blanket anonymity promise.</h3><p>Timing, wallet activity, public transaction data and reused identifiers may correlate actions. Stillwater does not prove that a person or wallet is untraceable.</p></div><div><h3>Your browser is part of the boundary.</h3><p>Secrets are held in memory and disappear on reload. A backup is sensitive plaintext. Malware, browser extensions, XSS, or a remote proving service can compromise private inputs.</p></div></div></section>
    <section className="technical-note"><div><span className="label">Selective disclosure in Compact</span><h2>A deliberate public surface.</h2><p><code>disclose()</code> marks values that cross into public ledger operations. The hidden score is constrained with an assertion. Only the room-scoped hash is disclosed for replay protection.</p><Link to="/ledger" className="text-link">Inspect the public side <ArrowRight size={16} /></Link></div><pre aria-label="Illustrative privacy boundary"><code>{`const score = get_private_score();\nassert(score >= claim_threshold,\n       "Threshold not met");\n\nconst secret = get_invite_secret();\nconst token = derive_redemption_token(\n  secret, room_id\n);\nredeemed_tokens.insert(disclose(token));`}</code></pre></section>
  </div>;
}
